name: Sync GitHub README with Docker Hub

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - README.md

jobs:
  github-docker:
    name: Sync GitHub README with Docker Hub
    runs-on: ubuntu-latest-8-cores

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate docker-compliant image name
        run:
          echo "IMAGE_NAME=$(echo ${GITHUB_REPOSITORY,,} | sed 's/docker-//')" | tee -a $GITHUB_ENV

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: ${{ env.IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
